### ISSUE TITLE
the memory occupied by the program is getting larger and larger

### ISSUE THREAD

**Issue by Teemoshan** [rpng/open_vins#86] opened 2020-07-21 05:37 UTC
![9ABF6A4447E8CA7AC763608040E13657](https://user-images.githubusercontent.com/46919904/88016899-100b7100-cb57-11ea-896d-40d6437ea3f4.jpg)
Hi, I encountered some problems in the process of using, the memory occupied by the program is getting larger and larger, as shown in the picture, MSCKF-VIO does not have this problem.

**Comment by goldbattle** [comment] 2020-07-21 13:07
Does this only happen when you run serial, or also the ros subscriber node?

**Comment by Teemoshan** [comment] 2020-07-21 14:40
![33B5FC6FEE4AF16FFA8FB0663166CDBA](https://user-images.githubusercontent.com/46919904/88068445-c9dbff00-cba2-11ea-9ea3-a77df3cf3bbb.jpg)
the ros subscriber node  also  takes up a lot of memory

**Comment by Teemoshan** [comment] 2020-07-22 01:43
When max_cameras is 1, the program is normal. But when I use two camera , the memory occupied by the program is getting larger. This also happens on the euroc dataset, you can also try.

**Comment by goldbattle** [comment] 2020-07-22 01:57
Yeah this isn't something that should be happening. Maybe something to do with visualization or how multicam tracks are handled. I will try to take a look and see if I can see anything.

**Comment by Teemoshan** [comment] 2020-09-02 01:30
Have you solved this problem？ @goldbattle

**Comment by goldbattle** [comment] 2020-09-05 03:36
I have not due to time constraints, hopefully I will soon, but if you have any further investigations feel free to post, thanks!

**Comment by kimyoungji** [comment] 2020-09-26 02:38
@goldbattle

I found that this is caused by line 151-159 in 'TrackKLT::feed_stereo'.
This code is about building optical flow pyramids using cv functions and threads. 
I don't know the exact reasons why using threads arouses memory leak, it was fine when I revise it as
    cv::buildOpticalFlowPyramid(img_left, imgpyr_left, win_size, pyr_levels);
    cv::buildOpticalFlowPyramid(img_right, imgpyr_right, win_size, pyr_levels);
I hope this will be helpful for your upcoming updates.
Thanks!

**Comment by goldbattle** [comment] 2020-09-30 17:52
Hi, I wasn't able to reproduce this on my side.
What version of OpenCV are you using @Teemoshan and @kimyoungji ?

**Comment by kimyoungji** [comment] 2020-10-01 04:45
Mine is opencv 3.3.1.

**Comment by goldbattle** [comment] 2020-12-01 15:48
This should be addressed in #117, valgrind doesn't report any memory leaks and we are switched over to smart points.
This might be specific to an OpenCV version, try upgrading if it is still an issue or use your above fix.

**Closed by goldbattle** 2020-12-01 15:48 UTC
Labels: bug, debugging
